services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Services
    Passioneight\PimcoreGoogleRecaptcha\Service\:
        resource: '../../Service'

    # Event Subscribers
    Passioneight\PimcoreGoogleRecaptcha\EventSubscriber\:
        resource: '../../EventSubscriber'

    # Validators
    Passioneight\PimcoreGoogleRecaptcha\Form\Validator\:
        resource: '../../Form/Validator'

    # Twig Extensions
    Passioneight\PimcoreGoogleRecaptcha\Twig\Extension\:
        resource: '../../Twig/Extension'
